# Generated by Django 3.2.6 on 2021-09-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_exercise_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-date', '-time']},
        ),
    ]
