# Generated by Django 3.2.6 on 2021-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
