# Generated by Django 3.2.6 on 2021-09-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_schedule_options'),
        ('main_app', '0007_weather_icon'),
    ]

    operations = [
    ]
