# Generated by Django 3.2.6 on 2021-08-31 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_exercise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('C', 'Calgary'), ('S', 'Saskatoon'), ('V', 'Vancouver'), ('T', 'Toronto'), ('M', 'Montreal')], default='C', max_length=1)),
                ('city_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
