# Generated by Django 3.2.6 on 2021-09-02 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_0006_alter_schedule_options_0007_weather_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
